name: CI/CD - MCU
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install tools
        run: exit 1

      - name: Compile code
        if: always()
        run: echo "hola!"
